version: "3"
services:
    chef-server:
        build:
            context: .
            args:
              WITH_MANAGE: 1
        image: trueability/chef-server:dev
        environment:
          EXTERNAL_URL: 'https://192.168.99.2'
          EXTERNAL_PORT: '8888'
        volumes:
            - "/data/chef-server/data:/var/opt"
        privileged: true
        ports:
            - "8888:8888"
